version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/.mvn"
    schedule:
      interval: "daily"
      time: "16:15"
    allow:
      - dependency-name: "com.gradle.*"
        dependency-type: "production"
