version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "16:25"
    allow:
      - dependency-name: "com.gradle:gradle-enterprise-maven-extension"
        dependency-type: "production"
      - dependency-name: "com.gradle:common-custom-user-data-maven-extension"
        dependency-type: "production"
