version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "16:25"
    allow:
      - dependency-name: "com.gradle:*"
        dependency-type: "production"
